### ISSUE TITLE
Make a Predictive Function to get the codeforces rating of a problem | Contest Analysis 

### ISSUE THREAD

**Issue by NayakPenguin** [Algolisted-Org/AlgoListed#169]
<img width="1005" alt="Screenshot 2023-10-18 at 9 53 59 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/23a39dec-8586-4a68-84c6-db4b06a99ce5">

The issue is to calculate the codeforces rating of a leetcode problem based on various factors such as 
- Number of people solved a problem
- Problem Level
- Number of people made wrong submissions 
- Problem Credit
- Inspiration was taken from which company (_Not for this issue_)
- Inspiration was taken from which round (_Not for this issue_)
- How much time top 100-250-500-750-1000 people took to solve the problem (_Not for this issue_)

Firstly find the bracket the total accepted count lies in. Now in this bracket apply polynomialic funtions. In the below example we have 11020 total number of users solving problem A, hence here the bracket becomes: (min : [600, 1500], max : [900, 10000]). 
<img width="817" alt="Screenshot 2023-10-18 at 9 59 48 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/8b1b978d-711c-4ba5-8db5-5c1de42d5f06">

Now user the other mentioned factors to predict the real rating of the problem. 

### Other problem brackets 
<img width="611" alt="Screenshot 2023-10-18 at 10 10 05 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/8d1fd159-275c-4582-af6a-0a68a0cc611e">
<img width="973" alt="Screenshot 2023-10-18 at 10 16 22 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/68baf4e8-a726-4f43-91dd-a02d9cc1b4f3">
<img width="1091" alt="Screenshot 2023-10-18 at 10 18 10 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/ec4aa1d8-e3ce-4f79-8e74-f2960cf5d623">

**Comment by priyam-03** [comment]
Hi @Nayaker I am interested to work this issue.

**Comment by Nayaker** [comment]
Amazing @priyam-03, I am assigning this issue to you.

**Comment by Nayaker** [comment]
@priyam-03 any update on this??

**Comment by priyam-03** [comment]
I will complete by tomorrow.

**Comment by PRIZZA21** [comment]
@NayakPenguin It seems this issue still exists, if its relevant still can I start working on it?

**Comment by NayakPenguin** [comment]
@PRIZZA21, thank you for your interest! However, this issue has been closed. Please feel free to explore new issues or create any you come across on the website.
