### ISSUE TITLE
Part of filter and preference feature

### ISSUE THREAD

**Issue by khamkarsuraj** [Algolisted-Org/AlgoListed#225]
**Related issue**
This issue is sub-task of issue #217. 

**Description**
In #217, the enhancement request was to implement filtering and tracking user preferences. But making all these changes in a single patch will causes dependency issues in future. To avoid this and isolate task so that we can distribute within multiple people, I am creating this task.
This task will be closed once done with below sub-tasks.

**Filtering Options**
- [x] Job Type
- [x] Experience Level
- [x] Location
- [ ] Status

**Preference Options**
- [ ] Position already filled
- [ ] Disinterest in position
- [ ] Interested position

If you are new to this task please read [Community Guidlines](https://github.com/Nayaker/AlgoListed/blob/main/README.md) and refer #224 which is proposal for task.

**Comment by khamkarsuraj** [comment]
@Nayaker,
Are you fine with creating sub-tasks like this to implementation of feature?

**Comment by Nayaker** [comment]
Yeah sure, I will 👍

**Comment by Nayaker** [comment]
@shadow-ryu have a look on these

**Comment by shadow-ryu** [comment]
okay

**Comment by shadow-ryu** [comment]
I've  completed the implementation location filtering, but I could use assistance with the status filter. Currently, there is no backend support for features such as 'like,' etc. Can you help with this?

**Comment by khamkarsuraj** [comment]
@shadow-ryu, will you link your PR with this issue so that I could have look at changes?

**Comment by Nayaker** [comment]
> I've completed the implementation location filtering, but I could use assistance with the status filter. Currently, there is no backend support for features such as 'like,' etc. Can you help with this? @Nayaker @khamkarsuraj

I think you should store them on the local storage for each user.

**Comment by shadow-ryu** [comment]
> > I've completed the implementation location filtering, but I could use assistance with the status filter. Currently, there is no backend support for features such as 'like,' etc. Can you help with this? @Nayaker @khamkarsuraj
> 
> I think you should store them on the local storage for each user.

will Look into it

**Comment by khamkarsuraj** [comment]
> > I've completed the implementation location filtering, but I could use assistance with the status filter. Currently, there is no backend support for features such as 'like,' etc. Can you help with this? @Nayaker @khamkarsuraj
> 
> I think you should store them on the local storage for each user.

I think storing information about like, dislike into `localStorage` is not that good idea. Because we might have 100 of records listed there and rendering webpage every time with that many local variable might slow downs the application.
We should think something else for that.

@Nayaker @shadow-ryu

**Comment by Nayaker** [comment]
Presently, Algolisted imposes constraints on the number of API calls we can make, prompting me to store data locally. Although this approach may introduce a slight slowdown to the application, the impact is expected to be relatively minor. However, I am open to exploring alternative methods that could mitigate this issue without relying heavily on API calls. If you have any suggestions or better approaches, I am eager to hear and discuss them.

@khamkarsuraj @shadow-ryu

**Comment by shadow-ryu** [comment]
if want to use local  save we can try  storing it in session storage

**Comment by shadow-ryu** [comment]
IndexedDB is more suitable for applications that require complex data storage, querying, and indexing, especially when dealing with large datasets and its long term storage

**Comment by shadow-ryu** [comment]
As much I know IndexedDB is more suitable  for  complex data storage, querying, and indexing and its long term storage.

**Comment by khamkarsuraj** [comment]
Sounds good. We have our approach ready then. @shadow-ryu Would you like to work on preferences?

**Comment by shadow-ryu** [comment]
@khamkarsuraj , I would love  to taken on  the task, but currently, my schedule is quite packed. If someone else is interested, they are more than welcome to take it on. I anticipate being available to address it in a day or two. If it's acceptable, I would like to recommend my friend for this task. @rohancodex

**Comment by Nayaker** [comment]
> @khamkarsuraj , I would love to taken on the task, but currently, my schedule is quite packed. If someone else is interested, they are more than welcome to take it on. I anticipate being available to address it in a day or two. If it's acceptable, I would like to recommend my friend for this task. @rohancodex

@khamkarsuraj ??

**Comment by khamkarsuraj** [comment]
> @khamkarsuraj ??

Waiting for reply from @rohancodex otherwise I am ready to work on this task.

**Comment by rohanattorinit** [comment]
@khamkarsuraj I'll take up on this task. Thanks!

**Comment by rohancodex** [comment]
@Nayaker Is there any design for the colors for the like, filled, not-interested icon interactions?

**Comment by Nayaker** [comment]
> @Nayaker Is there any design for the colors for the like, filled, not-interested icon interactions?

colors are not planned as of now, but try to keep the color structure similar to other pages like https://algolisted.com/coding-sheets/striver-sde-sheet

**Comment by khamkarsuraj** [comment]
Hey @rohancodex,
How is it going for you?

**Comment by rohanattorinit** [comment]
Hey @khamkarsuraj, was a busy week at work. I've started working on it. Should be done with the status filter by tonight.

**Comment by rohancodex** [comment]
Hey @khamkarsuraj @Nayaker , is there no unique field for the items of the opportunity table?
If so should I maybe combine 2 fields to make a unique field?

`
​{
contributor: "Atanu nayak",
date: "2023-11-22T18:30:00.000Z",
job_link: "https://careers.adobe.com/us/en/job/ADOBUSR141934EXTERNALENUS/2024-Intern-Machine-Learning-Engineer?utm_medium=phenom-feeds&source=LinkedIn&utm_source=linkedin",
job_title: "Adobe - ML",
location: "India",
magic_filter: "yes",
role: "Machine leaning",
salary_high: 12,
salary_low: 9,
source: "https://www.google.com/search?q=long_param",
type: "FTE",
years_exp: "Fresher"}
`

**Comment by khamkarsuraj** [comment]
Hello @rohancodex,
We already have a unique URL for every JSON record, but there are better ideas than storing this big string in `localStorage`. I would have used this URL to create a unique identifier using Hashing or something and held it in `localStorage`. This unique identifier can then be used as per the user's preference, like, dislike, etc.
First, store a unique identifier for each record in browser storage while loading the page.
Secondly, whenever the user clicks on any of the buttons, get its URL, convert it into a unique identifier and check with already stored unique identifiers; once found, mark it with the respective operation.
Take your time, no worries.

@Nayaker Thoughts?

**Comment by rohanattorinit** [comment]
I was thinking something like this might be more performant rather than hashing and getting back the string every time:
![image](https://github.com/Nayaker/AlgoListed/assets/111341927/c70eb057-1e91-477f-9fd8-91353335b04b)

**Comment by Nayaker** [comment]
> I was thinking something like this might be more performant rather than hashing and getting back the string every time: ![image](https://private-user-images.githubusercontent.com/111341927/289374091-c70eb057-1e91-477f-9fd8-91353335b04b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzQxOTksIm5iZiI6MTcwMjIzMzg5OSwicGF0aCI6Ii8xMTEzNDE5MjcvMjg5Mzc0MDkxLWM3MGViMDU3LTFlOTEtNDc3Zi05ZmQ4LTkxMzUzMzM1YjA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxODQ0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWEzZjdhYzBiZjc1YjU4MzU0NDJiOTQxMWI5MDA0Zjk5NmJlNjVmN2U0YzY1Y2E5YWIxZWY0NGY1OGZhMTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bU1rO7i7lruJ8SaIz54Km-pkrsWsf9lc3LK5TgEX4yI)


The regex may need adjustment since the link might not consistently have ```/job```. Besides that, I believe it is good. 

Additionally, regarding hashing, @shadow-ryu seemed to imply a concept similar to this unique key. However, I propose calculating it initially during or before mapping to facilitate direct matching with ```localStorage```. This approach eliminates the need to convert hashing back to a URL later on.

**Comment by Nayaker** [comment]
@rohanattorinit updates?

**Comment by NayakPenguin** [comment]
@khamkarsuraj can you please complete this issue?

**Comment by IAlgorithmia** [comment]
@NayakPenguin I would like to take up this task, may I?

**Comment by NayakPenguin** [comment]
@IAlgorithmia Thanks for the nudge! I'm planning to get back on the site. Yes, you can take up the task—happy to have you onboard! Let's revive this together.

**Comment by IAlgorithmia** [comment]
@NayakPenguin I've fixed some bugs that I had encountered, can you please review the changes and merge the PR if no issues arise. 

This PR may seem like only a small change to the original codebase but I wanted your review first. 
After you complete reviewing this, I'll move on to implementing the remaining features.

**Comment by IAlgorithmia** [comment]
@NayakPenguin done with this :)

**Comment by NayakPenguin** [comment]
Amazing work @IAlgorithmia, I will review it soon! 
PTAL @Mohit030802

**Comment by NayakPenguin** [comment]
Very clean code writing @IAlgorithmia 🚀

**Comment by IAlgorithmia** [comment]
Thank you @NayakPenguin 😊
