### ISSUE TITLE
Dark to light mode

### ISSUE THREAD

**Issue by KubasuIvanSakwa** [Algolisted-Org/AlgoListed#246]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

The side-nav remains in dark mode when the page is taggled to light mode is this a bug or it should work that way
![image](https://github.com/Algolisted-Org/AlgoListed/assets/72573043/b4511033-9d20-4065-80d9-36a0ccdf58ad)

**Comment by NayakPenguin** [comment]
It's a bug, try refreshing it will work! If it still doesn't then let us know @KubasuIvanSakwa

**Comment by KubasuIvanSakwa** [comment]
@NayakPenguin now it works it's fine
