### ISSUE TITLE
[ Improve ] Improve the feedback for the company-preparation page 

### ISSUE THREAD

**Issue by AayushSaini101** [Algolisted-Org/AlgoListed#258]
Change feedback to: Feature will be soon available instead of page not found

**Comment by kartik-chausali** [comment]
Hey can you provide a little more context about this one , on which url this issue persists ? I would like to work on this

**Comment by NayakPenguin** [comment]
Create a "Feature will be soon available" page. 

Example open - https://algolisted.com/company-preparation 

1. Please refrain from altering the existing 404 Not Found page; instead, create a new "Feature Coming Soon" page and link it accordingly.
2. Design a new UI; do not use the UI from the 404 Not Found page.

**Comment by NayakPenguin** [comment]
@kartik-chausali please let us know we you have any further queries.

**Comment by NayakPenguin** [comment]
#267 resolves the issue!
