### ISSUE TITLE
Save Tracking Button Status on "Opportunities" Page | LocalStorage Integration | @HacktoberFest 2024

### ISSUE THREAD

**Issue by NayakPenguin** [Algolisted-Org/AlgoListed#263]
### Problem:
On the **"Opportunities"** page, we have three tracking buttons: **"Filled," "Not Interested," and "Liked."** Currently, the status of these buttons is not persisted across sessions, so users lose their selection when they refresh the page or revisit the site.

<img width="961" alt="Screenshot 2024-10-10 at 5 35 57 PM" src="https://github.com/user-attachments/assets/0401a64f-4bd9-4533-ad56-362200eb41bf">

### Solution:
1. **Button Status Tracking**:
   - Each of the three buttons: **"Filled," "Not Interested," and "Liked"** should have its status saved locally in the browser using **localStorage**.
   
2. **LocalStorage Implementation**:
   - On button click, store the corresponding status (e.g., "filled," "no_interest," "liked") in **localStorage** based on the user's choice.
   - On page load, retrieve the status from **localStorage** and ensure the correct button is highlighted or marked as selected.

3. **Persistence Across Sessions**:
   - Ensure that when users refresh the page or revisit the site, their previously selected status for each opportunity is loaded from **localStorage** and displayed accordingly.

### Requirements:
- Experience working with **JavaScript and localStorage** to save and retrieve data.
- Ensure that this implementation does not interfere with the overall page performance.
- This task requires a basic understanding of DOM manipulation and browser storage mechanisms.

### Testing:
- After implementing, test thoroughly to ensure that the status persists across page refreshes and browser sessions for each opportunity.

---

**Open to Contributors:**
If you are familiar with working with localStorage in JavaScript and want to enhance the user experience on the "Opportunities" page, this task is for you! Please comment if you would like to claim this issue or need further clarification.

Happy coding! 💻🚀

**Comment by MehekFatima** [comment]
hi, I'm interested in solving this issue. I have experience with JavaScript and localStorage.

**Comment by NayakPenguin** [comment]
@MehekFatima Thank you for your interest in solving this issue. Feel free to get started, and if you have any questions or run into any issues, don't hesitate to reach out.

Issue assigned ✅

**Comment by palak-k5** [comment]
Hey,im interested in solving the issue,would like to contribute to it.

**Comment by NayakPenguin** [comment]
Thank you so much for your interest, @palak-k5! However, this issue has already been assigned to @MehekFatima :)

Keep an eye out for other open issues—your contributions are always welcome!

**Comment by NayakPenguin** [comment]
#264 resolves this issue!
