### ISSUE TITLE
Add working links for social icons and increase size of contributor and tech stack image for better visibility

### ISSUE THREAD

**Issue by Aditi2k5** [Algolisted-Org/AlgoListed#268]
links of socials not redirecting and would like to add working links if available

**Comment by NayakPenguin** [comment]
Hi @Aditi2k5, thank you for raising the issue! Could you please clarify which specific "working links for social icons" are not working? 

_Share some screenshots or links to page_

**Comment by Aditi2k5** [comment]
I mean the socials icons which are present do not redirect to any social
pages so I could ass relevant social links for them which could lead the
project maintainers socials

**Comment by NayakPenguin** [comment]
Cool @Aditi2k5, I am assigning this issue to you. 🚀 ✨

**Comment by Aditi2k5** [comment]
Hey the deployed url does not seem to work

________________________________

**Comment by Aditi2k5** [comment]
Also it doesnt seem to be running on a local server could you tell me which file i need to mainly use to make changes to the links
Thanks,
Aditi
________________________________

**Comment by NayakPenguin** [comment]
Hi @Aditi2k5, could you please share the screenshots of the issues you're encountering? This will help us resolve them more efficiently.

**Comment by Aditi2k5** [comment]
Is it possible to tell which file I need to run so that I can view the changes in my pc as the commans do not seem to work which i followed by the README file[cid:022891ac-5536-48bf-907b-b6da0d5c6f65]
________________________________

**Comment by NayakPenguin** [comment]
1. Fork and clone repo locally
2. Go inside client folder
3. Run > npm i --force
4. npm start

**Comment by Aditi2k5** [comment]
It works now thanks also would you want me to add any specific social media urls of yourself?

________________________________

**Comment by Aditi2k5** [comment]
@NayakPenguin hey could you check the pr?

**Comment by NayakPenguin** [comment]
Great work @Aditi2k5! Works perfectly 🎉
