### ISSUE TITLE
Add Missing Line Between Opportunity and Track in Table.

### ISSUE THREAD

**Issue by MehekFatima** [Algolisted-Org/AlgoListed#269]
**Describe the bug**
The border line between the "Opportunity" and "Track" columns in the UI is missing, which should visually separate them.

**To Reproduce**
1. Go to the opportunities
2. Look at the row containing job opportunities
3. The "Opportunity" and "Track" columns do not have a dividing line.
4. The visual separation is missing between the two columns.

**Expected behavior**
A border line should be present between the "Opportunity" and "Track" columns to clearly distinguish them.

**Screenshots**
![image](https://github.com/user-attachments/assets/973fe177-aa32-47c6-90fc-05274b16895c)

**Comment by MehekFatima** [comment]
I've created a pull request to address this issue. It adds the missing line between "Opportunity" and "Track" in the Table component. 

PR link: #271

**Comment by NayakPenguin** [comment]
Thanks for creating the issue @MehekFatima!
