### ISSUE TITLE
Issue: Clicking the icon does not redirect to the home page

### ISSUE THREAD

**Issue by Sathish111j** [Algolisted-Org/AlgoListed#274]
![image](https://github.com/user-attachments/assets/3f7266a4-f7a3-4ff2-a571-0fae0dc4c47a)

Description:
When clicking on the [icon/logo], the expected behavior is to navigate to the home page. However, nothing happens, and the page does not redirect as intended.

**Comment by khushalmajoka** [comment]
I have fixed the issue and now click on the top left Logo will redirect to home page.

PR: #275
