### ISSUE TITLE
API Auth or Encryption | Node JS Backend 

### ISSUE THREAD

**Issue by NayakPenguin** [Algolisted-Org/AlgoListed#99]
The rule is that only authorized users should be able to use the API, and we want to restrict calls to it from any unauthorized sources. To access the API, you'll need an authentication key stored in your environment settings. Also, try to do some encryption which will convert the values into other characters, and on the frontend side it can be extracted. 

Although CORS can help with this, it has some limitations. So, if you have a clever solution, please help us solve this problem in a better way!

**Comment by 0-mayurkaretha** [comment]
Hello @Nayaker 
I'd like to contribute, please assign me.

**Comment by Nayaker** [comment]
Awesome, because this is a somewhat complex issue, could you start by sending a simple introductory email to [nayak.primary@gmail.com](mailto:nayak.primary@gmail.com)?

**Comment by Nayaker** [comment]
@0-mayurkaretha would you be interested in working on the issue?

**Comment by 0-mayurkaretha** [comment]
sure, thanks.

**Comment by Nayaker** [comment]
@0-mayurkaretha 
_Can you please check your discord_

**Comment by Nayaker** [comment]
<img width="1234" alt="Screenshot 2023-10-06 at 7 21 45 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/647ba9c9-fb63-44d0-8beb-a04e6c3d3033">

**Comment by 0-mayurkaretha** [comment]
> <img alt="Screenshot 2023-10-06 at 7 21 45 PM" width="1234" src="https://user-images.githubusercontent.com/93304796/273228351-647ba9c9-fb63-44d0-8beb-a04e6c3d3033.png">

Here, implementing authorization means registering user and give them JWT token to be able to call api, but its not much difference. After they have a token they can call api whenever they want.

So another possible solution I am checking is to make api calls server-server side instead of client-server side. I will create PR after its done.

**Comment by Nayaker** [comment]
Awesome 💪🏻

**Comment by Nayaker** [comment]
https://api.cuvette.tech/api/v1/student/internship-post/active?pageNumber=1&sortByDate=true&stipendRange=[5000] I want something like this to be implemented here. 

<img width="489" alt="Screenshot 2023-10-08 at 2 27 07 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/e8f83011-a05b-4922-89c0-09e621fde844">

**Comment by surjendu104** [comment]
Is this issue still open? If yes and if no one working then I will love to work on it.
cc : @NayakPenguin

**Comment by NayakPenguin** [comment]
Thank you for your interest, @surjendu104. 

**Unfortunately, we're not working on this issue at the moment.** However, feel free to explore other issues and see if you can resolve any, or you can create new issues that you identify on the website.
